### PR TITLE
Integrate k6 using erwin's state machine

### PR DESCRIPTION
**Pull request by sacheendra**
@joe4dev I checked with a workload of 100 iterations multiple times and it seems to work
Could you run a longer test using a complex workload and see if it works?

### CODE REVIEW

**Comment by joe4dev** [comment]
great 👍  

yeah, I will do that once I have the app instrumented, so I can check the traces as well ...

**Comment by joe4dev** [comment]
@sacheendra I fixed lots of endpoints (partly due to deployment role issues, partly due to integer instead of string data types) and added working instrumentation for the entire app (except the Kinesis part, which is unsupported).

One issue remains for the commit photo scenario (see issue https://github.com/perfkit/hello-retail/issues/5). Do you have an idea what's wrong there?

**Comment by sacheendra** [comment]
Thanks! I had some of these fixes, but yours are more thorough. There is one more fix to isolate data between VUs. Don't merge yet

**Comment by joe4dev** [comment]
ok, great. Thank you!
It's also much easier to spot them once everything is instrumented 🙈  => 🙉

Hint: You can filter by error root cause in the XRay trace view:
Screenshot 2021-04-07 at 16 54 26


FYI: I also attempted to parallelize the deployment (although some of the dependencies are not fully clear): https://github.com/perfkit/hello-retail/pull/3/commits/9ee70bd3344be33648662f87de408e73aae61df3
So far, I haven't noticed any issues that wouldn't occur with the serial deployment as well 🤞 but feel free to revert that one.

**Comment by joe4dev** [comment]
Merging this for now as the app works overall at least more or less.

Some issues remain though:
* /sms endpoints for commit photo scenario always fails with an internal server error (500)
  * `CommitPhoto fails with "receive.js - UserError: Oops! We couldn't find your assignment. If you have registered and not completed your assignments, we will send one shortly.
at /var/task/receive.js:170:37"`
  * CW logs indicate that the photographer data somehow miss in the event. Validation error: `lib/kinesisHandler.js for product-catalog/catalog.js processEvent bad msg: - event with unsupported data schema (com.nordstrom/user-info/update-phone/1-0-0) observed.` report.js:61 fails in the writeToStream method when trying to access the phone of missing photographer `lambdaEvent.photographer.phone`
  * Might have to do with the logic behind the app expecting a certain order of event and correct mapping of photos to photographers etc. At least the StepFunction consistently fails:
Screenshot 2021-04-29 at 18 42 50
Screenshot 2021-04-29 at 18 43 13


Other (less predictable) issues:
* `ConditionalCheckFailedException: The conditional request failed
at features.constructor.captureAWSRequest` in processor.js:110 when registering photographer
* The traceId passed through Kinesis is sometimes undefined in dev-processor and product-builder. It seems that detecting the traceId in report.js and eventWriterApi.js works reliably but something in the event transformation or sourcing logic might not quite fit.
* Stepfunction execution already exists

**Pull request merged**
